const QUESTION_CATALOG = [
  {
    id: "required-summary",
    title: "All required questions summary",
    description: "Runs all mandatory and recommended demo questions with editable default years, states, and region.",
    endpoint: "/accidentinfoapi/answers/required-summary",
    method: "GET",
    fields: [
      { key: "personalInjuryYear", label: "Personal injury year", type: "year-select", defaultValue: 2023 },
      { key: "personalInjuryState", label: "Personal injury state", type: "state-select", defaultValue: "14" },
      { key: "firstState", label: "First availability state", type: "state-select", defaultValue: "05" },
      { key: "secondState", label: "Second availability state", type: "state-select", defaultValue: "13" },
      { key: "pedestrianYear", label: "Pedestrian year", type: "year-select", defaultValue: 2023 },
      { key: "pedestrianState", label: "Pedestrian state", type: "state-select", defaultValue: "11" },
      { key: "rateYear", label: "Passenger-car rate year", type: "year-select", defaultValue: 2023 },
      { key: "fatalYear", label: "Fatal ranking year", type: "year-select", defaultValue: 2024 },
      { key: "bicycleYear", label: "Bicycle year", type: "year-select", defaultValue: 2024 },
      { key: "bicycleRegion", label: "Bicycle region", type: "region-select", defaultValue: "Dresden" },
      { key: "zeroYear", label: "Zero-case year", type: "year-select", defaultValue: 2023 },
      { key: "zeroState", label: "Zero-case state", type: "state-select", defaultValue: "14" },
    ],
    fixedParams: {},
    answerShape: "summary",
  },
  {
    id: "earliest-accident-year",
    title: "Earliest accident year in the complete dataset",
    description: "Uses all Unfallatlas accident rows and returns MIN(accidents.year).",
    endpoint: "/accidentinfoapi/answers/earliest-accident-year",
    method: "GET",
    fields: [],
    fixedParams: {},
    answerShape: "single_value",
  },
  {
    id: "personal-injury-by-state",
    title: "Personal injury accidents by state and year",
    description: "Answers the Saxony 2023 question, but the state and year are editable.",
    endpoint: "/accidentinfoapi/answers/count",
    method: "GET",
    fields: [
      { key: "year", label: "Year", type: "year-select", required: true, defaultValue: 2023 },
      { key: "stateAgs", label: "Federal state", type: "state-select", required: true, defaultValue: "14" },
    ],
    fixedParams: { personalInjury: "true" },
    answerShape: "count",
  },
  {
    id: "state-availability",
    title: "Data available from year for a state",
    description: "Answers NRW and Mecklenburg-Western Pomerania availability questions.",
    endpoint: "/accidentinfoapi/answers/available-from",
    method: "GET",
    fields: [
      { key: "stateAgs", label: "Federal state", type: "state-select", required: true, defaultValue: "05" },
    ],
    fixedParams: {},
    answerShape: "single_value",
  },
  {
    id: "pedestrian-by-state",
    title: "Pedestrian accidents by state and year",
    description: "Answers the Berlin 2023 pedestrian question, but state and year are editable.",
    endpoint: "/accidentinfoapi/answers/count",
    method: "GET",
    fields: [
      { key: "year", label: "Year", type: "year-select", required: true, defaultValue: 2023 },
      { key: "stateAgs", label: "Federal state", type: "state-select", required: true, defaultValue: "11" },
    ],
    fixedParams: { pedestrian: "true" },
    answerShape: "count",
  },
  {
    id: "passenger-car-rate",
    title: "Traffic accidents per 100,000 passenger cars",
    description: "Cross-source query: Unfallatlas accident counts divided by Regionalatlas passenger-car stock.",
    endpoint: "/accidentinfoapi/answers/passenger-car-rate",
    method: "GET",
    fields: [
      { key: "year", label: "Accident year", type: "year-select", required: true, defaultValue: 2023 },
      { key: "limit", label: "Number of regions", type: "number", min: 1, max: 50, defaultValue: 10 },
    ],
    fixedParams: {},
    answerShape: "table",
  },
  {
    id: "top-fatal-districts",
    title: "Top districts with highest fatal accidents",
    description: "Ranks districts by fatal accident count for the selected year.",
    endpoint: "/accidentinfoapi/answers/top-fatal-districts",
    method: "GET",
    fields: [
      { key: "year", label: "Year", type: "year-select", required: true, defaultValue: 2024 },
      { key: "limit", label: "Number of districts", type: "number", min: 1, max: 20, defaultValue: 5 },
    ],
    fixedParams: {},
    answerShape: "table",
  },
  {
    id: "bicycle-by-region",
    title: "Bicycle accidents by region and year",
    description: "Answers the Dresden 2024 bicycle question, but the region and year are editable.",
    endpoint: "/accidentinfoapi/answers/count",
    method: "GET",
    fields: [
      { key: "year", label: "Year", type: "year-select", required: true, defaultValue: 2024 },
      { key: "regionName", label: "Region", type: "region-select", required: true, defaultValue: "Dresden" },
    ],
    fixedParams: { bicycle: "true" },
    answerShape: "count",
  },
  {
    id: "zero-accident-municipalities",
    title: "Municipalities with zero accidents",
    description: "Answers the Saxony 2023 zero-case question, but state and year are editable.",
    endpoint: "/accidentinfoapi/answers/zero-accident-municipalities",
    method: "GET",
    fields: [
      { key: "stateAgs", label: "Federal state", type: "state-select", required: true, defaultValue: "14" },
      { key: "year", label: "Year", type: "year-select", required: true, defaultValue: 2023 },
    ],
    fixedParams: {},
    answerShape: "list",
  },
  {
    id: "custom-count",
    title: "Custom accident count",
    description: "General count query for year, time, region, accident category, type, and participant flags.",
    endpoint: "/accidentinfoapi/answers/count",
    method: "GET",
    fields: [
      { key: "year", label: "Year", type: "year-select", required: true },
      { key: "month", label: "Month", type: "month-select" },
      { key: "weekday", label: "Weekday", type: "weekday-select" },
      { key: "hour", label: "Hour", type: "hour-select" },
      { key: "ags", label: "Exact AGS", type: "text", hint: "Official region key" },
      { key: "stateAgs", label: "Federal state", type: "state-select" },
      { key: "regionName", label: "Region name", type: "region-select" },
      { key: "category", label: "Accident category", type: "category-select" },
      { key: "type", label: "Accident type", type: "type-select" },
      { key: "personalInjury", label: "Personal injury", type: "checkbox" },
      { key: "pedestrian", label: "Pedestrian", type: "checkbox" },
      { key: "bicycle", label: "Bicycle", type: "checkbox" },
      { key: "car", label: "Car", type: "checkbox" },
      { key: "motorcycle", label: "Motorcycle", type: "checkbox" },
      { key: "fatal", label: "Fatal", type: "checkbox" },
    ],
    fixedParams: {},
    answerShape: "count",
  },
];

function getQuestionCatalog() {
  return QUESTION_CATALOG;
}

module.exports = {
  getQuestionCatalog,
};
